on:
  - push
jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1.1.0
        with:
          fqbn: "adafruit:samd:adafruit_pyportal_m4_titano"
          platforms: |
            - name: "adafruit:samd"
              source-url: "https://adafruit.github.io/arduino-board-index/package_adafruit_index.json"
              
          sketch-paths: |
            - ./HotWaterController.ino
          libraries: |
            - name: "Adafruit BusIO"
            - name: "Adafruit GFX Library"
            - name: "Adafruit HX8357 Library"
            - name: "Adafruit PCF8591"
            - name: "DallasTemperature"
            - name: "FreeRTOS_SAMD51"
            - name: "MQTT"
            - name: "OneWire"
            - name: "WiFiNINA"
